### ISSUE TITLE
Not working after newest update.

### ISSUE THREAD

**Issue by HaikenEdge** [zero318/BegoneWhatsNew#4] opened 2021-11-20 07:16 UTC
After the latest update, What's New is back.

**Comment by Wintar** [comment] 2021-11-20 09:24
I can confirm the same issue is happening on my steam library too.

**Comment by JakXLT** [comment] 2021-11-20 09:40
Can confirm cancer has relapsed.

**Comment by Aerophus** [comment] 2021-11-20 11:57
Try "libraryhome_UpdatesContainer" instead of "libraryhome_WhatsNew".

**Comment by Aho-Senpai** [comment] 2021-11-20 12:06
> `libraryhome_UpdatesContainer`
This does work, looks good 👍

**Comment by PseudoNymNZL** [comment] 2021-11-20 18:58
Same issue for me.  how do i apply this fix?  do i just have to wait until someone incorporates the change/does the merge?

**Comment by techmouse** [comment] 2021-11-20 20:22
> Try "libraryhome_UpdatesContainer" instead of "libraryhome_WhatsNew".

Can confirm solution works. Thank you kindly. 


> Same issue for me. how do i apply this fix? do i just have to wait until someone incorporates the change/does the merge?

Go to where ever you installed the skin to and edit /disablewhatsnew/resource/webkit.css.

Personally, I opted to keep two separate entries, in case Valve decides they want to roll it back.

`[class*="libraryhome_WhatsNew"] {
	display: none !important;
}
[class*="libraryhome_UpdatesContainer"] {
	display: none !important;
}`

Then you simply restart Steam.

**Comment by PseudoNymNZL** [comment] 2021-11-20 21:23
> > Try "libraryhome_UpdatesContainer" instead of "libraryhome_WhatsNew".
> 
> Can confirm solution works. Thank you kindly.
> 
> > Same issue for me. how do i apply this fix? do i just have to wait until someone incorporates the change/does the merge?
> 
> Go to where ever you installed the skin to and edit /disablewhatsnew/resource/webkit.css.
> 
> Personally, I opted to keep two separate entries, in case Valve decides they want to roll it back.
> 
> ```
> [class*="libraryhome_WhatsNew"] {
> 	display: none !important;
> }
> [class*="libraryhome_UpdatesContainer"] {
> 	display: none !important;
> }
> ```
> 
> Then you simply restart Steam.

Thank you!  For some reason my C:\Program Files (x86)\Steam\skins\whatsnewbegone\resource\webkit.css was radically different (had libraryhome_WhatsNew plus an extension TDG07 or something instead of simply libraryhome_WhatsNew, plus had a bunch of other stuff) and the substitution didn't work.  But now i understand where to look/what to do, i just downloaded the latest original skin, copied it to C:\Program Files (x86)\Steam\skins\whatsnewbegone**2**\, made the change from WhatsNew to UpdatesContainer, changed the skin from whatsnewbegone to whatsnewbegone2, and restarted Steam.  Worked fine thanks!

**Comment by vertigoelectric** [comment] 2021-11-21 05:14
> [class*="libraryhome_WhatsNew"] {
> 	display: none !important;
> }
> [class*="libraryhome_UpdatesContainer"] {
> 	display: none !important;
> }

Can you share how you are able to figure out what the class name is?  I'm not sure which file(s) to check.  If it changes again, I'd like to be able to dig into the code and find a fix for myself instead of waiting for someone else to post it online (although I must admit you guys got on this pretty face.  Well done!).

**Comment by techmouse** [comment] 2021-11-21 05:54
> > [class*="libraryhome_WhatsNew"] {
> > display: none !important;
> > }
> > [class*="libraryhome_UpdatesContainer"] {
> > display: none !important;
> > }
> 
> Can you share how you are able to figure out what the class name is? I'm not sure which file(s) to check. If it changes again, I'd like to be able to dig into the code and find a fix for myself instead of waiting for someone else to post it online (although I must admit you guys got on this pretty face. Well done!).

I'm curious of this as well. I grep'd the entirety of the Steam directory and the only result I got was the absolute monster of a file /.steam/steamui/css/6.css which was clearly never written by humans or for humans.

**Comment by vertigoelectric** [comment] 2021-11-21 06:50
Yeah I found that file as well but haven't had a chance to review it.

**Comment by AsheIsAmazing** [comment] 2021-11-24 10:20
> > [class*="libraryhome_WhatsNew"] {
> > display: none !important;
> > }
> > [class*="libraryhome_UpdatesContainer"] {
> > display: none !important;
> > }
> 
> Can you share how you are able to figure out what the class name is? I'm not sure which file(s) to check. If it changes again, I'd like to be able to dig into the code and find a fix for myself instead of waiting for someone else to post it online (although I must admit you guys got on this pretty face. Well done!).

I assume they used dev mode to inspect the element (use a steam shortcut with -dev).

**Comment by Unknow0059** [comment] 2022-04-21 20:39
If it's been fixed why isn't this pulled into the github code?
Or updated.
So people don't have to manually do it.
Or at least close this issue.

**Comment by Aho-Senpai** [comment] 2022-04-22 01:59
It has been fixed and merged. https://github.com/zero318/BegoneWhatsNew/pull/5. 
I'm guessing the repo owner just forgot to close this issue.

**Comment by zero318** [comment] 2022-05-30 21:48
Yup, forgetting to close the issue is exactly what happened. Consider it fixed. :)

**Closed by zero318** 2022-05-30 21:48 UTC
